language: python

matrix:
  include:
    - os: linux
      env:
        - PYTHON_VERSION=2.7
        - MINICONDA=Miniconda2-latest-Linux-x86_64.sh

    - os: linux
      env:
        - PYTHON_VERSION=3.6
        - MINICONDA=Miniconda3-latest-Linux-x86_64.sh

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=2.7
        - MINICONDA=Miniconda2-latest-MacOSX-x86_64.sh

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.6
        - MINICONDA=Miniconda3-latest-MacOSX-x86_64.sh

install:
  # download and install miniconda
  - wget https://repo.continuum.io/miniconda/$MINICONDA -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

  # useful for debugging any issues with conda
  - conda info -a

  # create the conda environment
  - conda create -q -n test-env python=$PYTHON_VERSION
  - source activate test-env

  # build the wheel
  - python setup.py bdist_wheel --universal

  # install the wheel and its dependencies
  - |
    for f in dist/SDF-*.whl; do
      pip install $f
    done

script:
  - cd tests
  - python -m unittest discover
  - cd ..

deploy:
  provider: pypi
  user: t-sommer
  password:
    secure: kZB9lfyKFiWSHk0B4llLBeD7cHxhP6bvFiNH0MK8CzlJeHzOyRnnYqD4xeAP1Y/SEY+My72vt/97v2ZfnxxsKuR3fwCjv7/97B2s2WsMtigm3sbBe2Z3xR3DEh+gvuwheElIExbLhpllnXFSAv/oCvQ8F/gJSW2kxzUSIys5NMB0qwinG97hhBb92XjstDaYW12DmKKy1gzz2xqZ7ulluyLXIsV8LjPA3dM0AhtXwtWFhyMMV8MZY+nh7MnenIpvjpPk+7B72L8s2mQlkofWGMjSiyLCQUKeOA6jT+UnWDXkBM/TkxXO4E7ixSfO4sKFo1j9TVsBr23VnypVh6rA0UU0n+WcpGEXMc+/pI3yecyD2h0R7J5EyX0x17eTy14xA07xqa1chVjgsbfFIi7vDAE1dvZMGnTtYUA/i6XSAcDggx7yF/Ry6ALYmH1/NduTaBlpahn7A793MpIgiuA0z2IBmQAbCLIUVftmn9GG0l+qtlmqtvnmcBEfBwJgjRcDfDZ1U2wsVoZps/rMgppNXfyu6DyGCIVBX7xmKUpxpWBpTzUq+qpHxVFEsR5HGyu8LuWCJZmJHjE9KSMWhGS1Bcv/K1xolRdKtl7vR+OTxlzYqnxRf729O0cC67E7fE3Htg0IKaX4tK7XVavu1cWhVQSHjP2KcQPuDWUCrso7328=
  distributions: bdist_wheel --universal
  skip_cleanup: true
